/**
 * @generated
 * @file ListingCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://stone-6adb3b.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Link from "../webflow_modules/Basic/components/Link";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * Props for {@link ListingCard}
 *
 * Property result card: media, photo count, agent strip, address, bed/bath/car, open times, contact link.
 */
export type ListingCardProps = {
  /** Agent display name, joined from the agents table via agentIds.*/
  agentAgentName?: React.ReactNode;
  /** Agent phone, joined from the agents table via agentIds.*/
  agentAgentPhone?: React.ReactNode;
  /** Target for the Contact Agent link.*/
  agentContactUrl?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  /** Bathroom count.*/
  listingBathrooms?: number;
  /** Bedroom count.*/
  listingBedrooms?: number;
  /** Carspace count.*/
  listingCarspaces?: number;
  /** Street-level address. Suburb is rendered separately.*/
  listingDisplayAddress?: React.ReactNode;
  /** Agentbox listing ID. Always a string - never store as a number.*/
  listingListingId?: string;
  /** Number of photos, derived from images.length.*/
  listingPhotoCount?: number;
  /** Price as rendered. Use priceValue for filtering, never this.*/
  listingPriceDisplay?: React.ReactNode;
  /** Suburb name.*/
  listingSuburb?: React.ReactNode;
  /** Hides the open times block when there is no open home.*/
  openHomeHasOpenTimes?: boolean;
  /** Preformatted open home date. Not a canonical Listing field.*/
  openHomeOpenDate?: React.ReactNode;
  /** Preformatted open home time range. Not a canonical Listing field.*/
  openHomeOpenTime?: React.ReactNode;
};

/**
 * ListingCard
 *
 * Property result card: media, photo count, agent strip, address, bed/bath/car, open times, contact link.
 *
 * @see {@link https://stone-6adb3b.design.webflow.com | Source site in Webflow}
 */
export function ListingCard({
  agentAgentName = "Jane Smith",
  agentAgentPhone = "1234 567 890",

  agentContactUrl = {
    href: "#",
  },

  listingBathrooms = 2,
  listingBedrooms = 3,
  listingCarspaces = 1,
  listingDisplayAddress = "1/38 West Market Street",
  listingListingId = "0000000",
  listingPhotoCount = 20,
  listingPriceDisplay = "$1,250,000",
  listingSuburb = "Richmond",
  openHomeHasOpenTimes = true,
  openHomeOpenDate = "Wed 4th March",
  openHomeOpenTime = "4:15 pm - 4:30 pm",
}: ListingCardProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"listing-card"}
        data-address={""}
        data-agent-name={""}
        data-agent-phone={""}
        data-agent-photo={""}
        data-baths={""}
        data-beds={""}
        data-cars={""}
        data-contact-url={""}
        data-image={""}
        data-listing-card={""}
        data-listing-template={""}
        data-listing-url={""}
        data-open-date={""}
        data-open-time={""}
        data-photo-count={""}
        data-price={""}
        data-suburb={""}
        id={listingListingId}
        tag={"div"}
      >
        <Block className={"listing-media"} tag={"div"}>
          <Block className={"photo-count"} tag={"div"}>
            {formatNumber(-1)(listingPhotoCount)}
          </Block>
          <Block className={"media-placeholder"} tag={"div"} />
          <Block className={"agent-strip"} tag={"div"}>
            <Block className={"agent-avatar"} tag={"div"} />
            <Block className={"agent-details"} tag={"div"}>
              <Block className={"agent-name"} tag={"div"}>
                {agentAgentName}
              </Block>
              <Block className={"agent-phone"} tag={"div"}>
                {agentAgentPhone}
              </Block>
            </Block>
          </Block>
        </Block>
        <Block className={"listing-body"} tag={"div"}>
          <Block className={"listing-suburb"} tag={"div"}>
            {listingSuburb}
          </Block>
          <Block className={"listing-address"} tag={"div"}>
            {listingDisplayAddress}
          </Block>
          <Block className={"listing-price"} tag={"div"}>
            {listingPriceDisplay}
          </Block>
          <Block className={"feature-row"} tag={"div"}>
            <Block className={"feature-box"} tag={"div"}>
              <Block className={"feature-icon"} tag={"div"} />
              <Block className={"feature-value"} tag={"div"}>
                {formatNumber(-1)(listingBedrooms)}
              </Block>
            </Block>
            <Block className={"feature-box"} tag={"div"}>
              <Block className={"feature-icon"} tag={"div"} />
              <Block className={"feature-value"} tag={"div"}>
                {formatNumber(-1)(listingBathrooms)}
              </Block>
            </Block>
            <Block className={"feature-box"} tag={"div"}>
              <Block className={"feature-icon"} tag={"div"} />
              <Block className={"feature-value"} tag={"div"}>
                {formatNumber(-1)(listingCarspaces)}
              </Block>
            </Block>
          </Block>
          {openHomeHasOpenTimes ? (
            <Block className={"open-times"} tag={"div"}>
              <Block className={"open-times-label"} tag={"div"}>
                {"Open times:"}
              </Block>
              <Block className={"open-times-row"} tag={"div"}>
                <Block className={"open-date"} tag={"div"}>
                  {openHomeOpenDate}
                </Block>
                <Block className={"open-time"} tag={"div"}>
                  {openHomeOpenTime}
                </Block>
              </Block>
            </Block>
          ) : null}
          <Link
            button={false}
            className={"contact-agent"}
            options={agentContactUrl}
          >
            {"Contact Agent"}
          </Link>
        </Block>
      </Block>
    </div>
  );
}
